<?
$this->jQuery()
		->setLocalPath($this->baseUrl() . '/js/jquery-1.6.1.min.js')
		->addJavascriptFile('/js/imagePreview.js')
		->addJavascriptFile('/js/modernizr-1.7.min.js');
?>
<!DOCTYPE HTML>
<html>
	<head>
		<meta charset=utf-8>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>

		<title>Keboola Object</title>

		<?=$this->jQuery();?>

		<link rel="stylesheet" type="text/css" href="/css/52framework/reset.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/css3.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/general.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/52framework/forms.css" media="screen" />
    	<link rel="stylesheet" type="text/css" href="/css/main.css" media="screen" />
	</head>

	<body>
		<div class="keboolaObject">
			<?=$this->layout()->content;?>
		</div>
	</body>
</html>


